### ISSUE TITLE
Review feedback

### ISSUE THREAD

**Issue by beverloo** [rknoll/content-index#1]
Thanks for publishing this! Some suggestions.

**Intro**
- "This is not a great user experience." Why not? (Undiscoverability.) What's the impact to the developer? It'd be great to highlight _why_ this is interesting for developers.
- "...developers can _expose_ fresh content..." - what does this mean?
- "This allows the user to browser..." - no, it doesn't. It allows the browser to provide UI that then allows the user to browse.
- "...and potentially search on-device for a specific article." - This sounds too hypothetical. I'd focus on mentioning some examples of where this data could go and what it enables: help users discover available content whilst offline, add extra details to browsing history, participate in on-device search, etc..

**Why**
- This very much focuses on the offline case. I would also detail other discoverability reasons: particularly rich highlights might be worth mentioning.

**Combined with other APIs**
- While the example with the Periodic Sync API is apt, by using it you're proposing something on top of a proposal, which is perceived as a risk. I would suggest using the Push API instead w/ pre-caching content on a breaking news notification.
- Rather than using `await` in a loop, which makes for a sequential operation, store the promises in an array and then `await` for `Promise.all()`, making it a parallel operation.

There also are a few other things I think would be good to mention:

- Privacy and security. While obvious, still good practice to state it.
- Quality enforcement. Since this isn't providing a storage layer, _how_ does it solve the problem of making content available online? (This proposal addresses the developer incentive.) What if a developer puts a million items in their cache?
- Related: why does this interface live off the `ServiceWorkerRegistration`?
- Reasoning as to why there are different categories of data.
- Alternatives. Many browsers already suggest content to users, why is that not sufficient? Where do other _hot_ projects like Web Packaging come in?

I'm sure you've seen the following document, but just in case:
https://github.com/w3ctag/w3ctag.github.io/blob/master/explainers.md

**Comment by rknoll** [comment]
Thanks a lot! I've addressed your comments in e4e7bcf, let me know what you think 🙂
