### ISSUE TITLE
Potential as a spam vector

### ISSUE THREAD

**Issue by quasicomputational** [rknoll/content-index#10]
This is a potential spam vector. Browsers should be prepared to deal with malicious websites registering a whole pile of bogus resources to fill up the offline content discovery interface. This isn't a problem with the spec *per se* since this is in the realm of implementation decisions.

I think something like being able to manually hide all registrations from a particular registrable domain will be needed, as well as whatever automatic anti-spam mechanisms get put in place - probably central registrable domain nolists.

I think this will warrant a note in the security section, if only so that it's on implementers' radars.

**Comment by tyohan** [comment]
Practically, it's possible to spam  the offline content discovery interface because there is no permission to add content to index. I'm worry this could make the web publishers think as a way to bring more visitors like push notification. So they will add the their latest contents to content indexing.

**Comment by rayankans** [comment]
Yeah, a website can register as many content index entries as it wants. After all, it's just telling the browser about available content. It's the browser's job to sort through the entries, rank them, and show the appropriate UI.

For example, Chrome is experimenting with grouping entries from the same domain together into an expandable list. That's one way to solve the spam problem.

The explainer still needs an `abuse considerations` section. The spam issue will be mentioned there when it's added.

**Comment by limhenry** [comment]
Is it better to have the options to let user to delete all articles (from a domain) in one single click? (Currently user need to delete the article one by one)

Or maybe let the user to have the options to blacklist the domain from using the Content Indexing API?

Related Discussion: https://twitter.com/nekrtemplar/status/1283273532420562944

**Comment by rayankans** [comment]
Hi @limhenry. Thanks for the context.

Specs should allow for flexibility in the UI for browsers, so this isn't the sort of thing that can be enforced in a web standard. I'd recommend filing an issue in crbug.com under the `Blink>ContentIndex` component so Chrome specifically can look into that.

It's important to remember that the Content Index API is just metadata about already available content. A website can still have all of those articles stored without using the Content Indexing API. Clearing all Content Index entries would just clear the metadata provided by the website.
