### ISSUE TITLE
Privacy implications

### ISSUE THREAD

**Issue by quasicomputational** [rknoll/content-index#11]
It bears explicitly noting that offline content registrations are like history in how they make revealing browsing history easy, rather than like cookies/etc which require work to leak browsing history. These should be cleared whenever history is cleared, not just when a total site data purge happens.

While this isn't *exactly* new with this spec - websites can track your browsing history and re-display it - it does make this sort of leakage a lot more likely, and in particular it's likely to be shown by the browser, rather than the website itself.

**Comment by rayankans** [comment]
I think this falls in line with expectations since deleting history doesn't unregister Service Workers or invalidate push subscriptions.

I'd rather have Content Index entries being purged as a side effect of a Service Worker being unregistered
