### ISSUE TITLE
Why only one icon type/size? (look at web app manifest)

### ISSUE THREAD

**Issue by kenchris** [rknoll/content-index#2]

**Comment by rayankans** [comment]
@kenchris I'm not sure what the advantage of that would be. An icon URL would be enough, and follows suit of what the Notifications API does.

**Comment by quasicomputational** [comment]
Is this relying on `Client-Hints` to send the pixel density, and `Accept` to indicate which formats are acceptable, and then using server-driven content negotiation? I don't think that covers variant icon sizes (which header field would you set for that?): an icon with lots of pixels for display on a high-density display at a small size is likely different to an icon with lots of pixels for display on a low-density display at a large size.

Web Manifests has provision for the browser picking its preferred icon size, format, etc, which I think is a better design.

**Comment by rayankans** [comment]
I've given this some more thought, and I think it makes sense to pass a sequence of `ImageResource`s for the reasons covered above and browser UI flexibility.

I've updated the explainer, but I'll keep this issue open in case more people have thoughts on the matter.
