### ISSUE TITLE
launchUrl is incorrectly capitalized

### ISSUE THREAD

**Issue by domenic** [rknoll/content-index#21]
It should be launchURL, per https://w3ctag.github.io/design-principles/#casing-rules and https://url.spec.whatwg.org/#url-apis-elsewhere

**Comment by domenic** [comment]
This is not fixed:

- https://github.com/WICG/content-index#general-usage
- https://github.com/WICG/content-index#combined-with-other-apis
- https://wicg.github.io/content-index/spec/#example
- https://wicg.github.io/content-index/spec/#dom-contentdescription-launchurl
- https://wicg.github.io/content-index/spec/#content-index-add

**Comment by rayankans** [comment]
I updated all instances besides the dictionary property. Other dictionaries tend to use `url` or `fooUrl`.

**Comment by domenic** [comment]
The point of this issue was to update the dictionary property, since that's what the actual public API is that the design principles guidelines apply to.

If there are other dictionaries failing to follow the design principles, please let me know so they can be corrected!

Note: `url` is correct since it is the first word. `fooUrl` is incorrect since it is the second word.

**Comment by domenic** [comment]
Thank you!
