### ISSUE TITLE
Why have both id and launchUrl?

### ISSUE THREAD

**Issue by quasicomputational** [rknoll/content-index#8]
What's the point of the `id` field? Why isn't (the absolutised value of) `launchUrl` a primary key? If it's not and I'm misunderstanding something, maybe an example should be shown where there are non-unique `launchUrl` values.

**Comment by rayankans** [comment]
It's a bit awkward to call `index.delete` with a `launchUrl`. Having a tag makes more sense from an API point of view, even if the `launchUrl` should be unique per registration.
